language: scala

scala:
  2.11.8

jdk:
  - oraclejdk8

script:
  - sbt clean coverage test coverageReport

after_success:
- bash <(curl -s https://codecov.io/bash) -t 46bb38a3-8592-429d-9740-6660f90937c3
